import { useState } from 'react';
import { ArrowLeft,ArrowRight,Download,History,Plus,Pencil,CalendarDays,Check } from 'lucide-react';
import { displayDate,errorMessage,fromManilaInput,manilaInput,rpc } from './lib';
import { canReview,canRecord,FINDING_NAMES,STATUS_NAMES,type Bootstrap,type CaseDetail,type CaseSummary,type Participant,type Action } from './types';
import { Alert,Badge,Empty,Field,Loading,Modal,PageHeading,ReasonDialog,useLoad } from './ui';

export function CaseTable({items,onOpen}:{items:CaseSummary[];onOpen:(id:string)=>void}){
 if(!items.length)return <Empty title="No recorded cases">No case is stored in this system for the selected search and school year.</Empty>;
 return <div className="table-scroll"><table className="records-table"><thead><tr><th>Case / student</th><th>Behavior</th><th>Incident</th><th>Stage</th><th><span className="sr-only">Open</span></th></tr></thead><tbody>{items.map(c=><tr key={c.id}><td><button className="record-link" onClick={()=>onOpen(c.id)}>{c.case_no}</button><span className="table-secondary">{c.participant_names}</span></td><td>{c.behavior_name}<span className="table-secondary">SY {c.year_label}</span></td><td>{displayDate(c.happened_at)}<span className="table-secondary">{c.location}</span></td><td><Badge value={c.status}/></td><td><button className="icon-button" aria-label={'Open '+c.case_no} onClick={()=>onOpen(c.id)}><ArrowRight size={18}/></button></td></tr>)}</tbody></table></div>
}
export function CasesList({boot,onOpen,onCreate}:{boot:Bootstrap;onOpen:(id:string)=>void;onCreate:()=>void}){
 const [query,setQuery]=useState(''),[submitted,setSubmitted]=useState(''),[year,setYear]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(0);
 const load=useLoad(()=>rpc<{items:CaseSummary[];total:number}>('list_cases',{p_query:submitted,p_year_id:year||null,p_status:status,p_page:page}),[submitted,year,status,page]);
 return <><PageHeading eyebrow="JHS & SHS" title="Case records" description="Search the office’s recorded incidents across school years." actions={canRecord(boot.member.role)&&<button className="button" onClick={onCreate}><Plus size={17}/>Record incident</button>}/>
 <section className="panel no-pad"><form className="filter-bar" onSubmit={e=>{e.preventDefault();setPage(0);setSubmitted(query.trim())}}><Field label="Search"><input value={query} maxLength={160} onChange={e=>setQuery(e.target.value)} placeholder="Name, school ID, or case number"/></Field><Field label="School year"><select value={year} onChange={e=>{setYear(e.target.value);setPage(0)}}><option value="">All school years</option>{boot.years.map(y=><option key={y.id} value={y.id}>{y.label}</option>)}</select></Field><Field label="Case stage"><select value={status} onChange={e=>{setStatus(e.target.value);setPage(0)}}><option value="">All stages</option>{Object.entries(STATUS_NAMES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><button className="button secondary">Search</button></form>
 {load.loading?<Loading/>:load.error?<div className="panel-body"><Alert>{load.error}</Alert></div>:load.data&&<><CaseTable items={load.data.items} onOpen={onOpen}/><div className="pagination"><span>{load.data.total} case{load.data.total!==1?'s':''} · Page {page+1}</span><div><button className="button secondary small" disabled={page===0} onClick={()=>setPage(v=>v-1)}>Previous</button><button className="button secondary small" disabled={(page+1)*20>=load.data.total} onClick={()=>setPage(v=>v+1)}>Next</button></div></div></>}</section></>
}
type DialogState={kind:'status';status:string}|{kind:'finding';p:Participant}|{kind:'action';action:Action;status:string}|{kind:'event'}|{kind:'proposal'}|{kind:'history'}|null;
export function CaseRecord({id,boot,onBack,onEdit,onStudent,onChanged}:{id:string;boot:Bootstrap;onBack:()=>void;onEdit:(c:CaseDetail)=>void;onStudent:(id:string)=>void;onChanged:()=>void}){
 const load=useLoad(()=>rpc<CaseDetail>('get_case',{p_id:id}),[id]);
 const [dialog,setDialog]=useState<DialogState>(null),[error,setError]=useState(''),[exporting,setExporting]=useState(false),[finding,setFinding]=useState('substantiated');
 const refresh=()=>{load.reload();onChanged()};
 if(load.loading)return <Loading/>;
 if(load.error)return <Alert>{load.error}<button className="text-button" onClick={load.reload}>Retry</button></Alert>;
 const c=load.data!;const member=boot.member;const reviewer=canReview(member.role);const writable=canRecord(member.role)&&!['closed','resolved'].includes(c.status);
 const editable=writable&&(reviewer||(c.status==='draft'&&c.created_by===member.user_id));
 let next: string[]=({draft:['reported'],reported:['under_review'],under_review:['monitoring','resolved','closed'],reopened:['monitoring','resolved','closed'],monitoring:['under_review','resolved'],resolved:['closed','reopened'],closed:['reopened']} as Record<string,string[]>)[c.status]||[];
 next=next.filter(s=>member.role==='principal'||(reviewer&&!['closed','reopened'].includes(s))||(c.status==='draft'&&c.created_by===member.user_id&&canRecord(member.role)));
 return <><button className="back-button" onClick={onBack}><ArrowLeft size={16}/>Case records</button><PageHeading eyebrow={'SY '+c.year_label} title={c.case_no} description={c.behavior_name} actions={<><button className="button secondary" disabled={exporting} onClick={async()=>{setExporting(true);setError('');try{await (await import('./exports')).exportWord({caseId:id})}catch(e){setError(errorMessage(e))}finally{setExporting(false)}}}><Download size={17}/>{exporting?'Preparing…':'Export Word'}</button>{editable&&<button className="button" onClick={()=>onEdit(c)}><Pencil size={16}/>Update record</button>}</>}/>
 {error&&<Alert>{error}</Alert>}
 <div className="case-meta"><Badge value={c.status}/><span>Logged {displayDate(c.created_at,true)} by {c.created_by_name}</span><span>Version {c.version}</span><button className="text-button" onClick={()=>setDialog({kind:'history'})}><History size={15}/>History</button></div>
 <div className="case-columns"><div className="case-main"><section className="panel"><h2>Incident account</h2><div className="facts"><div><span>When</span><strong>{displayDate(c.happened_at,true)}</strong></div><div><span>Where</span><strong>{c.location}</strong></div></div><p className="preserve">{c.summary}</p></section>
 <section className="panel"><h2>Students and statements</h2>{c.participants.map(p=><article className="student-statement" key={p.id}><div className="row between"><div><button className="record-link student-name" onClick={()=>onStudent(p.student_id!)}>{p.full_name}</button><p className="subtle small">{p.school_id} · Age {p.age} · Grade {p.grade}, {p.section}{p.strand?' · '+p.strand:''}</p></div><Badge value={p.role}/></div>
 {p.role==='respondent'&&<div className="finding-block"><div><span className="field-caption">FINDING</span><strong>{FINDING_NAMES[p.finding||'pending']}</strong><p className="small">{p.prior_confirmed||0} prior confirmed incident{p.prior_confirmed===1?'':'s'} of this behavior this school year.</p></div>{member.role==='principal'&&['under_review','reopened'].includes(c.status)&&<button className="button secondary small" onClick={()=>{setFinding(p.finding==='not_substantiated'?'not_substantiated':'substantiated');setDialog({kind:'finding',p})}}>Record finding</button>}</div>}
 {p.finding_reason&&<p className="preserve">{p.finding_reason}</p>}
 <div className="statement-box"><span className="field-caption">{p.role==='affected'?'AFFECTED STUDENT’S STATEMENT':'STUDENT STATEMENT'}</span>{p.statement_status==='recorded'?<><p className="preserve">{p.statement}</p><small>Taken {displayDate(p.statement_at,true)}</small></>:<p className="subtle">{p.statement_status.replaceAll('_',' ')}.</p>}</div></article>)}</section>
 <section className="panel"><div className="section-header"><h2>Office timeline</h2>{writable&&<button className="button secondary small" onClick={()=>setDialog({kind:'event'})}><Plus size={15}/>Meeting or note</button>}</div>{!c.events.length?<Empty title="No meetings or notes yet">Record office conferences, guardian contact, decisions, and follow-ups here.</Empty>:<div className="timeline">{c.events.map(e=><article key={e.id}><div className="timeline-icon"><CalendarDays size={16}/></div><div><div className="row between"><h3>{e.title}</h3><span className="small subtle">{displayDate(e.happened_at,true)}</span></div><p className="preserve">{e.body}</p>{e.attendees&&<p className="small"><strong>Participants:</strong> {e.attendees}</p>}<p className="small subtle">Logged by {e.author} · {displayDate(e.created_at,true)}</p>{e.follow_up_on&&<div className="followup-pill">Follow-up: {displayDate(e.follow_up_on)}{(e as typeof e&{follow_up_done:boolean}).follow_up_done?<span> · Completed</span>:writable&&<button className="text-button" onClick={async()=>{try{await rpc('complete_followup',{p_event_id:e.id});refresh()}catch(err){setError(errorMessage(err))}}}><Check size={14}/>Mark done</button>}</div>}</div></article>)}</div>}</section></div>
 <aside className="case-aside"><section className="panel"><h2>Case stage</h2><p className="small subtle">Each change is recorded with its reason and author.</p>{next.length?<div className="stage-buttons">{next.map(s=><button className="button secondary" key={s} onClick={()=>setDialog({kind:'status',status:s})}>{s==='reported'?'Submit for review':s==='under_review'?'Begin / resume review':s==='monitoring'?'Move to monitoring':s==='resolved'?'Mark resolved':s==='closed'?'Close case':'Reopen case'}<ArrowRight size={15}/></button>)}</div>:<p className="subtle small">Your role has no stage changes available.</p>}</section>
 <section className="panel"><div className="section-header"><h2>Actions</h2>{reviewer&&['under_review','reopened','monitoring'].includes(c.status)&&<button className="icon-button" aria-label="Propose action" onClick={()=>setDialog({kind:'proposal'})}><Plus size={20}/></button>}</div><p className="small subtle">Proposals require the principal’s approval before taking effect.</p>{!c.actions.length?<p className="subtle">No actions recorded.</p>:c.actions.map(a=><article className="action-card" key={a.id}><div className="row between"><h3 className="capitalize">{a.kind}</h3><Badge value={a.status}/></div><strong className="small">{a.student_name}</strong><p className="preserve small">{a.description}</p><p className="small subtle">{displayDate(a.starts_on)} → {displayDate(a.ends_on)}</p>{a.approved_by_name&&<p className="small subtle">Approved by {a.approved_by_name} · {displayDate(a.approved_at)}</p>}{a.completion_note&&<p className="small preserve">{a.completion_note}</p>}<div className="action-controls">{member.role==='principal'&&a.status==='proposed'&&<button className="button small" onClick={()=>setDialog({kind:'action',action:a,status:'active'})}>Approve action</button>}{reviewer&&a.status==='active'&&<button className="button secondary small" onClick={()=>setDialog({kind:'action',action:a,status:'completed'})}>Record completion</button>}{member.role==='principal'&&['proposed','active'].includes(a.status)&&<button className="text-button danger" onClick={()=>setDialog({kind:'action',action:a,status:'cancelled'})}>Cancel action</button>}</div></article>)}</section></aside></div>
 {dialog?.kind==='status'&&<ReasonDialog title={'Change stage to '+STATUS_NAMES[dialog.status]} description="Confirm the next stage and record the basis for this change." onClose={()=>setDialog(null)} onSubmit={async reason=>{await rpc('set_case_status',{p_id:id,p_version:c.version,p_status:dialog.status,p_reason:reason});refresh()}}/>}
 {dialog?.kind==='finding'&&<ReasonDialog title={'Finding · '+dialog.p.full_name} description="Record the school’s finding after the required review and due process." onClose={()=>setDialog(null)} onSubmit={async reason=>{await rpc('record_finding',{p_participant_id:dialog.p.id,p_version:c.version,p_finding:finding,p_reason:reason});refresh()}}><Field label="Finding"><select value={finding} onChange={e=>setFinding(e.target.value)}><option value="substantiated">Substantiated</option><option value="not_substantiated">Not substantiated</option></select></Field></ReasonDialog>}
 {dialog?.kind==='action'&&<ReasonDialog title={dialog.status==='active'?'Approve disciplinary action':dialog.status==='completed'?'Record verified completion':'Cancel action'} description={dialog.status==='active'?'Confirm that the action and its dates match the school’s authorized decision.':'Record the reason or evidence for this update.'} onClose={()=>setDialog(null)} onSubmit={async reason=>{await rpc('update_action',{p_id:dialog.action.id,p_version:dialog.action.version,p_status:dialog.status,p_note:reason});refresh()}}/>}
 {dialog?.kind==='event'&&<EventForm caseId={id} onClose={()=>setDialog(null)} onSaved={refresh}/>}
 {dialog?.kind==='proposal'&&<ActionForm record={c} onClose={()=>setDialog(null)} onSaved={refresh}/>}
 {dialog?.kind==='history'&&<HistoryModal caseId={id} onClose={()=>setDialog(null)}/>}
 </>
}
function EventForm({caseId,onClose,onSaved}:{caseId:string;onClose:()=>void;onSaved:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 return <Modal title="Record meeting or office note" onClose={onClose}><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await rpc('add_case_event',{p_case_id:caseId,p_payload:{kind:f.get('kind'),title:f.get('title'),body:f.get('body'),happened_at:fromManilaInput(String(f.get('when'))),attendees:f.get('attendees'),follow_up_on:f.get('followup')}});onSaved();onClose()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}}><div className="form-grid"><Field label="Record type"><select name="kind"><option value="meeting">Office / committee meeting</option><option value="parent_contact">Parent / guardian contact</option><option value="note">Office note</option><option value="resolution">Resolution discussion</option><option value="appeal">Appeal</option><option value="correction">Correction / clarification</option></select></Field><Field label="Meeting / event date and time"><input required type="datetime-local" name="when" defaultValue={manilaInput()}/></Field></div><Field label="Title"><input name="title" required minLength={2} maxLength={200}/></Field><Field label="Participants / attendees"><input name="attendees" maxLength={1000} placeholder="Names and roles of those present"/></Field><Field label="Discussion, outcome, and next steps"><textarea name="body" required minLength={2} maxLength={20000} rows={5}/></Field><Field label="Follow-up due date (optional)"><input name="followup" type="date"/></Field>{error&&<Alert>{error}</Alert>}<div className="form-actions"><button className="button secondary" type="button" disabled={busy} onClick={onClose}>Cancel</button><button className="button" disabled={busy}>{busy?'Saving…':'Save office record'}</button></div></form></Modal>
}
function ActionForm({record,onClose,onSaved}:{record:CaseDetail;onClose:()=>void;onSaved:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[kind,setKind]=useState('warning');
 return <Modal title="Propose an action" onClose={onClose}><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await rpc('propose_action',{p_case_id:record.id,p_payload:{participant_id:f.get('participant'),kind,description:f.get('description'),starts_on:f.get('start'),ends_on:f.get('end')}});onSaved();onClose()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}}><p>Record an action permitted by the school’s policy. It will remain a proposal until the principal approves it.</p><Field label="Action type"><select value={kind} onChange={e=>setKind(e.target.value)}>{['warning','counseling','probation','suspension','expulsion','other'].map(k=><option key={k} value={k}>{k[0].toUpperCase()+k.slice(1)}</option>)}</select></Field><Field label="Student"><select name="participant" required>{record.participants.filter(p=>p.role==='respondent'||kind==='counseling').map(p=><option key={p.id} value={p.id}>{p.full_name} · {p.role}</option>)}</select></Field><Field label="Action details and school-policy basis"><textarea name="description" required minLength={5} maxLength={10000} rows={5}/></Field><div className="form-grid"><Field label="Start date"><input name="start" type="date" required/></Field><Field label={'End date'+(['probation','suspension'].includes(kind)?'':' (if applicable)')}><input name="end" type="date" required={['probation','suspension'].includes(kind)}/></Field></div>{error&&<Alert>{error}</Alert>}<div className="form-actions"><button className="button secondary" type="button" onClick={onClose} disabled={busy}>Cancel</button><button className="button" disabled={busy}>{busy?'Saving…':'Save proposal'}</button></div></form></Modal>
}
function HistoryModal({caseId,onClose}:{caseId:string;onClose:()=>void}){
 const load=useLoad(()=>rpc<{id:string;case_version:number;reason:string;changed_at:string;author:string;snapshot:CaseDetail}[]>('case_history',{p_id:caseId}),[caseId]);
 return <Modal title="Preserved case history" onClose={onClose}>{load.loading?<Loading/>:load.error?<Alert>{load.error}</Alert>:!load.data?.length?<p>No earlier versions have been recorded.</p>:load.data.map(r=><details className="history-item" key={r.id}><summary>Version {r.case_version} · {displayDate(r.changed_at,true)} · {r.author}</summary><p><strong>Reason:</strong> {r.reason}</p><p><strong>Previous stage:</strong> {STATUS_NAMES[r.snapshot.status]}</p><p className="preserve">{r.snapshot.summary}</p>{r.snapshot.participants.map(p=><div key={p.id}><strong>{p.full_name} · {p.role} · {FINDING_NAMES[p.finding||'pending']}</strong><p className="small">Grade {p.grade}, {p.section} · Age {p.age}</p><p className="preserve">{p.statement||'No statement recorded.'}</p></div>)}</details>)}</Modal>
}
